import { MdOutlineFileDownload } from "react-icons/md";
import { CiImageOn, CiFaceSmile } from "react-icons/ci";
import { GrUpgrade } from "react-icons/gr";
import {
  LuActivity,
  LuAlignHorizontalJustifyStart,
  LuAlignHorizontalSpaceBetween,
  LuApple,
  LuAlarmCheck,
  LuAtSign,
  LuCheckCircle,
  LuFolderOpen,
  LuHeart,
  LuLoader,
  LuPencilLine,
} from "react-icons/lu";
import {
  AiFillBell,
  AiFillCamera,
  AiFillFire,
  AiFillGithub,
  AiFillOpenAI,
  AiFillTrophy,
  AiOutlineBranches,
  AiOutlineIe,
  AiOutlineLineChart,
  AiOutlinePlus,
  AiOutlineStar,
  AiOutlineTool,
} from "react-icons/ai";
import {
  FaBars,
  FaBroadcastTower,
  FaCcMastercard,
  FaCommentDots,
  FaDownload,
  FaFolderOpen,
  FaGripHorizontal,
  FaInfinity,
  FaMagic,
  FaMoon,
  FaPlusSquare,
  FaRegCheckCircle,
  FaRegGrin,
  FaRupeeSign,
  FaRegEdit,
} from "react-icons/fa";

export const icons = {
  MdOutlineFileDownload,
  FaRegEdit,
  CiImageOn,
  GrUpgrade,
  CiFaceSmile,
  AiFillBell,
  AiFillCamera,
  AiFillFire,
  AiFillGithub,
  AiFillOpenAI,
  AiFillTrophy,
  AiOutlineBranches,
  AiOutlineIe,
  AiOutlineLineChart,
  AiOutlinePlus,
  AiOutlineStar,
  AiOutlineTool,
  FaBars,
  FaBroadcastTower,
  FaCcMastercard,
  FaCommentDots,
  FaDownload,
  FaFolderOpen,
  FaGripHorizontal,
  FaInfinity,
  FaMagic,
  FaMoon,
  FaPlusSquare,
  FaRegCheckCircle,
  FaRegGrin,
  FaRupeeSign,
  LuActivity,
  LuAlignHorizontalSpaceBetween,
  LuAlignHorizontalJustifyStart,
  LuApple,
  LuAlarmCheck,
  LuAtSign,
  LuCheckCircle,
  LuFolderOpen,
  LuHeart,
  LuLoader,
  LuPencilLine,
};
